language: cpp
before_script:
# Install Boost
  - sudo apt-get update -qq
  - sudo apt-get install libboost-thread-dev libboost-system-dev libboost-log-dev
script:
  - mkdir build
  - (cd build && cmake ..)
  - (cd build && make VERBOSE=1)
  # Run Program
  - ./build/client www.google.com http
after_script:
  # Some Test output
  - ls -la build/